services:
  app:
    image: phonebook-frontend
    build:
      context: ./phonebook-frontend
      dockerfile: Dockerfile
    container_name: phonebook-front
    environment:
      - VITE_BASE_URL=
    expose:
      - 80

  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./phonebook-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo_data:/data/db

  server:
    build:
      context: ./phonebook-backend
      dockerfile: Dockerfile
    container_name: phonebook-backend
    volumes:
      - ./phonebook-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8080:80
    container_name: phonebook-reverse-proxy-prod
    depends_on:
      - app

volumes:
  mongo_data: